DINO/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import HomeView, TvGenre, MovieGenre, SearchViewSeries, SearchViewMovies,signup, OrderView, MovieDetailView, SeriesDetailView, add_to_cart, checkoutformView,removecart, deletecart
app_name = "home"

urlpatterns =[
    path('',HomeView.as_view(), name='home'),
    path('movie/<slug>', MovieDetailView.as_view(), name='movie'),
    path('series/<slug>', SeriesDetailView.as_view(), name='series'),
    path('tGenre',TvGenre.as_view(), name='tvgenre'),
    path('mGenre',MovieGenre.as_view(), name='moviegenre'),
    path('searchmovies',SearchViewMovies.as_view(), name='searchmovies'),
    path('searchseries',SearchViewSeries.as_view(), name='searchseries'),
    path('signup',signup,name= 'signup'),
    path('cart',OrderView.as_view(),name='cart'),
    path('add-to-cart/<slug>',add_to_cart, name='add-to-cart'),
    path('checkout',checkoutformView, name='checkout'),
    path('removecart/<slug>', removecart, name='removecart'),
    path('deletecart/<slug>', deletecart, name='deletecart'),
]

templates/MovieGenre.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<div class="movie-items">
	<div class="container">
		<div class="row ipad-width">

			<div class="col-md-8">
				<div class="title-hd">
					<h2></h2>

					<a href="#" class="viewall"><i class="ion-ios-arrow-right"></i></a>
				</div>
				<div class="title-hd">
					<h2></h2>
					<a href="#" class="viewall">View all <i class="ion-ios-arrow-right"></i></a>
				</div>
				<!--For Genre1-->
				<div class="tabs">
						<ul class="tab-links-2">
							<li ><a href="#tab21">SUPERHERO</a></li>
						</ul>
						<div class="tab-content">
				        <div id="tab21" class="tab active">
				            <div class="row">
				            	<div class="slick-multiItem">
									{% for t in Genre1%}
				            		<div class="slide-it">
				            			<div class="movie-item">
					            			<div class="mv-img">
					            				<img src="{{ t.Image.url }}" alt="" width="185" height="284">
					            			</div>
					            			<div class="hvr-inner">
					            				<a  href="{{ t.get_movie_url}} "> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6><a href="#">{{ t.Title}}</a></h6>
<!--					            				<p><i class="ion-android-star"></i><span>{{ t.Imbd_rating }}</span> /10</p>-->
					            			</div>
					            		</div>
										<p><i class="ion-android-star"></i><span>{{ t.Imdb_rating }}</span> /10</p>
				            		</div>
									{% endfor %}
				            	</div>
				            </div>
				        </div>
				    </div>
				</div>
				<!--For Genre2-->
				<div class="tabs">
						<ul class="tab-links-2">
							<li ><a href="#tab21">ACTION</a></li>
						</ul>
						<div class="tab-content">
				        <div id="tab21" class="tab active">
				            <div class="row">
				            	<div class="slick-multiItem">
									{% for t in Genre2%}
				            		<div class="slide-it">
				            			<div class="movie-item">
					            			<div class="mv-img">
					            				<img src="{{ t.Image.url }}" alt="" width="185" height="284">
					            			</div>
					            			<div class="hvr-inner">
					            				<a  href="{{ t.get_movie_url}} "> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6><a href="#">{{ t.Title}}</a></h6>
<!--					            				<p><i class="ion-android-star"></i><span>{{ t.Imbd_rating }}</span> /10</p>-->
					            			</div>
					            		</div>
										<p><i class="ion-android-star"></i><span>{{ t.Imdb_rating }}</span> /10</p>
				            		</div>
									{% endfor %}
				            	</div>
				            </div>
				        </div>
				    </div>
				</div>
				<!--For Genre3-->
				<div class="tabs">
						<ul class="tab-links-2">
							<li ><a href="#tab21">COMEDY</a></li>
						</ul>
						<div class="tab-content">
				        <div id="tab21" class="tab active">
				            <div class="row">
				            	<div class="slick-multiItem">
									{% for t in Genre3%}
				            		<div class="slide-it">
				            			<div class="movie-item">
					            			<div class="mv-img">
					            				<img src="{{ t.Image.url }}" alt="" width="185" height="284">
					            			</div>
					            			<div class="hvr-inner">
					            				<a  href="{{ t.get_movie_url}} "> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6><a href="#">{{ t.Title}}</a></h6>
<!--					            				<p><i class="ion-android-star"></i><span>{{ t.Imbd_rating }}</span> /10</p>-->
					            			</div>
					            		</div>
										<p><i class="ion-android-star"></i><span>{{ t.Imdb_rating }}</span> /10</p>
				            		</div>
									{% endfor %}
				            	</div>
				            </div>
				        </div>
				    </div>
				</div>
				<!--For Genre4 and so on-->
				<div class="tabs">
						<ul class="tab-links-2">
							<li ><a href="#tab21">SCI-FY</a></li>
						</ul>
						<div class="tab-content">
				        <div id="tab21" class="tab active">
				            <div class="row">
				            	<div class="slick-multiItem">
									{% for t in Genre4%}
				            		<div class="slide-it">
				            			<div class="movie-item">
					            			<div class="mv-img">
					            				<img src="{{ t.Image.url }}" alt="" width="185" height="284">
					            			</div>
					            			<div class="hvr-inner">
					            				<a  href="{{ t.get_movie_url}} "> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6><a href="#">{{ t.Title}}</a></h6>
<!--					            				<p><i class="ion-android-star"></i><span>{{ t.Imbd_rating }}</span> /10</p>-->
					            			</div>
					            		</div>
										<p><i class="ion-android-star"></i><span>{{ t.Imdb_rating }}</span> /10</p>
				            		</div>
									{% endfor %}
				            	</div>
				            </div>
				        </div>
				    </div>
				</div>
				<div class="tabs">
						<ul class="tab-links-2">
							<li ><a href="#tab21">ANIMATITON</a></li>
						</ul>
						<div class="tab-content">
				        <div id="tab21" class="tab active">
				            <div class="row">
				            	<div class="slick-multiItem">
									{% for t in Genre5%}
				            		<div class="slide-it">
				            			<div class="movie-item">
					            			<div class="mv-img">
					            				<img src="{{ t.Image.url }}" alt="" width="185" height="284">
					            			</div>
					            			<div class="hvr-inner">
					            				<a  href="{{ t.get_movie_url}} "> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6><a href="#">{{ t.Title}}</a></h6>
<!--					            				<p><i class="ion-android-star"></i><span>{{ t.Imbd_rating }}</span> /10</p>-->
					            			</div>
					            		</div>
										<p><i class="ion-android-star"></i><span>{{ t.Imdb_rating }}</span> /10</p>
				            		</div>
									{% endfor %}
				            	</div>
				            </div>
				        </div>
				    </div>
				</div>
				<div class="tabs">
						<ul class="tab-links-2">
							<li ><a href="#tab21">DRAMA</a></li>
						</ul>
						<div class="tab-content">
				        <div id="tab21" class="tab active">
				            <div class="row">
				            	<div class="slick-multiItem">
									{% for t in Genre6%}
				            		<div class="slide-it">
				            			<div class="movie-item">
					            			<div class="mv-img">
					            				<img src="{{ t.Image.url }}" alt="" width="185" height="284">
					            			</div>
					            			<div class="hvr-inner">
					            				<a  href="{{ t.get_movie_url}} "> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6><a href="#">{{ t.Title}}</a></h6>
<!--					            				<p><i class="ion-android-star"></i><span>{{ t.Imbd_rating }}</span> /10</p>-->
					            			</div>
					            		</div>
										<p><i class="ion-android-star"></i><span>{{ t.Imdb_rating }}</span> /10</p>
				            		</div>
									{% endfor %}
				            	</div>
				            </div>
				        </div>
				    </div>
				</div>
				<div class="tabs">
						<ul class="tab-links-2">
							<li ><a href="#tab21">HORROR</a></li>
						</ul>
						<div class="tab-content">
				        <div id="tab21" class="tab active">
				            <div class="row">
				            	<div class="slick-multiItem">
									{% for t in Genre7%}
				            		<div class="slide-it">
				            			<div class="movie-item">
					            			<div class="mv-img">
					            				<img src="{{ t.Image.url }}" alt="" width="185" height="284">
					            			</div>
					            			<div class="hvr-inner">
					            				<a  href="{{ t.get_movie_url}} "> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6><a href="#">{{ t.Title}}</a></h6>
<!--					            				<p><i class="ion-android-star"></i><span>{{ t.Imbd_rating }}</span> /10</p>-->
					            			</div>
					            		</div>
										<p><i class="ion-android-star"></i><span>{{ t.Imdb_rating }}</span> /10</p>
				            		</div>
									{% endfor %}
				            	</div>
				            </div>
				        </div>
				    </div>
				</div>
				<div class="tabs">
						<ul class="tab-links-2">
							<li ><a href="#tab21">ADVENTURE</a></li>
						</ul>
						<div class="tab-content">
				        <div id="tab21" class="tab active">
				            <div class="row">
				            	<div class="slick-multiItem">
									{% for t in Genre8%}
				            		<div class="slide-it">
				            			<div class="movie-item">
					            			<div class="mv-img">
					            				<img src="{{ t.Image.url }}" alt="" width="185" height="284">
					            			</div>
					            			<div class="hvr-inner">
					            				<a  href="{{ t.get_movie_url}} "> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6><a href="#">{{ t.Title}}</a></h6>
<!--					            				<p><i class="ion-android-star"></i><span>{{ t.Imbd_rating }}</span> /10</p>-->
					            			</div>
					            		</div>
										<p><i class="ion-android-star"></i><span>{{ t.Imdb_rating }}</span> /10</p>
				            		</div>
									{% endfor %}
				            	</div>
				            </div>
				        </div>
				    </div>
				</div>
			</div>
		</div>
	</div>
</div>



{% endblock %}

templates/TvGenre.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<div class="movie-items">
	<div class="container">
		<div class="row ipad-width">

			<div class="col-md-8">
				<div class="title-hd">
					<h2></h2>

					<a href="#" class="viewall"><i class="ion-ios-arrow-right"></i></a>
				</div>
				<div class="title-hd">
					<h2></h2>
					<a href="#" class="viewall">View all <i class="ion-ios-arrow-right"></i></a>
				</div>
				<!--For Genre1-->
				<div class="tabs">
						<ul class="tab-links-2">
							<li ><a href="#tab21">SUPERHERO</a></li>
						</ul>
						<div class="tab-content">
				        <div id="tab21" class="tab active">
				            <div class="row">
				            	<div class="slick-multiItem">
									{% for t in Genre1%}
				            		<div class="slide-it">
				            			<div class="movie-item">
					            			<div class="mv-img">
					            				<img src="{{ t.Image.url }}" alt="" width="185" height="284">
					            			</div>
					            			<div class="hvr-inner">
					            				<a  href="{{ t.get_series_url}} "> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6><a href="#">{{ t.Title}}</a></h6>
<!--					            				<p><i class="ion-android-star"></i><span>{{ t.Imbd_rating }}</span> /10</p>-->
					            			</div>
					            		</div>
										<p><i class="ion-android-star"></i><span>{{ t.Imdb_rating }}</span> /10</p>
				            		</div>
									{% endfor %}
				            	</div>
				            </div>
				        </div>
				    </div>
				</div>
				<!--For Genre2-->
				<div class="tabs">
						<ul class="tab-links-2">
							<li ><a href="#tab21">ACTION</a></li>
						</ul>
						<div class="tab-content">
				        <div id="tab21" class="tab active">
				            <div class="row">
				            	<div class="slick-multiItem">
									{% for t in Genre2%}
				            		<div class="slide-it">
				            			<div class="movie-item">
					            			<div class="mv-img">
					            				<img src="{{ t.Image.url }}" alt="" width="185" height="284">
					            			</div>
					            			<div class="hvr-inner">
					            				<a  href="{{ t.get_series_url}} "> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6><a href="#">{{ t.Title}}</a></h6>
<!--					            				<p><i class="ion-android-star"></i><span>{{ t.Imbd_rating }}</span> /10</p>-->
					            			</div>
					            		</div>
										<p><i class="ion-android-star"></i><span>{{ t.Imdb_rating }}</span> /10</p>
				            		</div>
									{% endfor %}
				            	</div>
				            </div>
				        </div>
				    </div>
				</div>
				<!--For Genre3-->
				<div class="tabs">
						<ul class="tab-links-2">
							<li ><a href="#tab21">COMEDY</a></li>
						</ul>
						<div class="tab-content">
				        <div id="tab21" class="tab active">
				            <div class="row">
				            	<div class="slick-multiItem">
									{% for t in Genre3%}
				            		<div class="slide-it">
				            			<div class="movie-item">
					            			<div class="mv-img">
					            				<img src="{{ t.Image.url }}" alt="" width="185" height="284">
					            			</div>
					            			<div class="hvr-inner">
					            				<a  href="{{ t.get_series_url}} "> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6><a href="#">{{ t.Title}}</a></h6>
<!--					            				<p><i class="ion-android-star"></i><span>{{ t.Imbd_rating }}</span> /10</p>-->
					            			</div>
					            		</div>
										<p><i class="ion-android-star"></i><span>{{ t.Imdb_rating }}</span> /10</p>
				            		</div>
									{% endfor %}
				            	</div>
				            </div>
				        </div>
				    </div>
				</div>
				<!--For Genre4 and so on-->
				<div class="tabs">
						<ul class="tab-links-2">
							<li ><a href="#tab21">SCI-FY</a></li>
						</ul>
						<div class="tab-content">
				        <div id="tab21" class="tab active">
				            <div class="row">
				            	<div class="slick-multiItem">
									{% for t in Genre4%}
				            		<div class="slide-it">
				            			<div class="movie-item">
					            			<div class="mv-img">
					            				<img src="{{ t.Image.url }}" alt="" width="185" height="284">
					            			</div>
					            			<div class="hvr-inner">
					            				<a  href="{{ t.get_series_url}} "> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6><a href="#">{{ t.Title}}</a></h6>
<!--					            				<p><i class="ion-android-star"></i><span>{{ t.Imbd_rating }}</span> /10</p>-->
					            			</div>
					            		</div>
										<p><i class="ion-android-star"></i><span>{{ t.Imdb_rating }}</span> /10</p>
				            		</div>
									{% endfor %}
				            	</div>
				            </div>
				        </div>
				    </div>
				</div>
				<div class="tabs">
						<ul class="tab-links-2">
							<li ><a href="#tab21">ANIMATITON</a></li>
						</ul>
						<div class="tab-content">
				        <div id="tab21" class="tab active">
				            <div class="row">
				            	<div class="slick-multiItem">
									{% for t in Genre5%}
				            		<div class="slide-it">
				            			<div class="movie-item">
					            			<div class="mv-img">
					            				<img src="{{ t.Image.url }}" alt="" width="185" height="284">
					            			</div>
					            			<div class="hvr-inner">
					            				<a  href="{{ t.get_series_url}} "> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6><a href="#">{{ t.Title}}</a></h6>
<!--					            				<p><i class="ion-android-star"></i><span>{{ t.Imbd_rating }}</span> /10</p>-->
					            			</div>
					            		</div>
										<p><i class="ion-android-star"></i><span>{{ t.Imdb_rating }}</span> /10</p>
				            		</div>
									{% endfor %}
				            	</div>
				            </div>
				        </div>
				    </div>
				</div>
				<div class="tabs">
						<ul class="tab-links-2">
							<li ><a href="#tab21">DRAMA</a></li>
						</ul>
						<div class="tab-content">
				        <div id="tab21" class="tab active">
				            <div class="row">
				            	<div class="slick-multiItem">
									{% for t in Genre6%}
				            		<div class="slide-it">
				            			<div class="movie-item">
					            			<div class="mv-img">
					            				<img src="{{ t.Image.url }}" alt="" width="185" height="284">
					            			</div>
					            			<div class="hvr-inner">
					            				<a  href="{{ t.get_series_url}} "> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6><a href="#">{{ t.Title}}</a></h6>
<!--					            				<p><i class="ion-android-star"></i><span>{{ t.Imbd_rating }}</span> /10</p>-->
					            			</div>
					            		</div>
										<p><i class="ion-android-star"></i><span>{{ t.Imdb_rating }}</span> /10</p>
				            		</div>
									{% endfor %}
				            	</div>
				            </div>
				        </div>
				    </div>
				</div>
				<div class="tabs">
						<ul class="tab-links-2">
							<li ><a href="#tab21">HORROR</a></li>
						</ul>
						<div class="tab-content">
				        <div id="tab21" class="tab active">
				            <div class="row">
				            	<div class="slick-multiItem">
									{% for t in Genre7%}
				            		<div class="slide-it">
				            			<div class="movie-item">
					            			<div class="mv-img">
					            				<img src="{{ t.Image.url }}" alt="" width="185" height="284">
					            			</div>
					            			<div class="hvr-inner">
					            				<a  href="{{ t.get_series_url}} "> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6><a href="#">{{ t.Title}}</a></h6>
<!--					            				<p><i class="ion-android-star"></i><span>{{ t.Imbd_rating }}</span> /10</p>-->
					            			</div>
					            		</div>
										<p><i class="ion-android-star"></i><span>{{ t.Imdb_rating }}</span> /10</p>
				            		</div>
									{% endfor %}
				            	</div>
				            </div>
				        </div>
				    </div>
				</div>
				<div class="tabs">
						<ul class="tab-links-2">
							<li ><a href="#tab21">ADVENTURE</a></li>
						</ul>
						<div class="tab-content">
				        <div id="tab21" class="tab active">
				            <div class="row">
				            	<div class="slick-multiItem">
									{% for t in Genre8%}
				            		<div class="slide-it">
				            			<div class="movie-item">
					            			<div class="mv-img">
					            				<img src="{{ t.Image.url }}" alt="" width="185" height="284">
					            			</div>
					            			<div class="hvr-inner">
					            				<a  href="{{ t.get_series_url}} "> Read more <i class="ion-android-arrow-dropright"></i> </a>
					            			</div>
					            			<div class="title-in">
					            				<h6><a href="#">{{ t.Title}}</a></h6>
<!--					            				<p><i class="ion-android-star"></i><span>{{ t.Imbd_rating }}</span> /10</p>-->
					            			</div>
					            		</div>
										<p><i class="ion-android-star"></i><span>{{ t.Imdb_rating }}</span> /10</p>
				            		</div>
									{% endfor %}
				            	</div>
				            </div>
				        </div>
				    </div>
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<!--[if IE 7]>
<html class="ie ie7 no-js" lang="en-US">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8 no-js" lang="en-US">
<![endif]-->
<!--[if !(IE 7) | !(IE 8)  ]><!-->
<html lang="en" class="no-js">


<head>

	<title>Movies and TV shows</title>
	<meta charset="UTF-8">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="">
	<link rel="profile" href="#">

    <!--Google Font-->
    <link rel="stylesheet" href='http://fonts.googleapis.com/css?family=Dosis:400,700,500|Nunito:300,400,600' />
	<!-- Mobile specific meta -->
	<meta name=viewport content="width=device-width, initial-scale=1">
	<meta name="format-detection" content="telephone-no">

	<!-- CSS files -->
	<link rel="stylesheet" href="{% static 'css/plugins.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

{% include 'navbar.html' %}

{% block content%}
{% endblock content %}

{% include 'footer.html' %}

</body>
</html>

templates/navbar.html
{% load static %}



<div id="preloader">
    <img class="logo" src="{% static 'images/logo1.png' %}" alt="" width="119" height="58">
    <div id="status">
        <span></span>
        <span></span>
    </div>
</div>

<div class="login-wrapper"  id="signup-content" value="sign-in" name = 'submit'>
    <div class="login-content">
        <a href="#" class="close">x</a>
        <h3>sign up</h3>
        <form method="POST" >
			{% csrf_token %}
			{% for message in messages %}
			{{ message }}
			{% endfor %}
            <div class="row">
                 <label for="username-2">
                    Username:
                    <input type="text" name="username" id="username-2" placeholder="Hugh Jackman"  required="required" />
                </label>
            </div>

            <div class="row">
                <label for="email-2">
                    your email:
                    <input type="text" name="email" id="email-2" placeholder=""  required="required" />
                </label>
            </div>
             <div class="row">
                <label for="password-2">
                    Password:
                    <input type="password" name="password" id="password-2" placeholder=""  required="required" />
                </label>
            </div>
             <div class="row">
                <label for="repassword-2">
                    re-type Password:
                    <input type="password" name="password1" id="repassword-2" placeholder=""  required="required" />
                </label>
            </div>
           <div class="row">
             <button type="submit">sign up</button>
           </div>
        </form>
    </div>
</div>
<!--end of signup form popup-->

<!-- BEGIN | Header -->
<header class="ht-header">
	<div class="container">
		<nav class="navbar navbar-default navbar-custom">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header logo">
				    <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					    <span class="sr-only">Toggle navigation</span>
					    <div id="nav-icon1">
							<span></span>
							<span></span>
							<span></span>
						</div>
				    </div>
				    <a href="index-2.html"><img class="logo" src="{% static 'images/logo1.png' %}" alt="" width="119" height="58"></a>
			    </div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav flex-child-menu menu-left">
						<li class="hidden">
							<a href="#page-top"></a>
						</li>
						<li class="dropdown first">
							<a href="/" >
							Home
							</a>
						</li>
						<li class="dropdown first">
							<a href="/mGenre" >
							movies
							</a>
							<ul class="dropdown-menu level1">
								<li class="dropdown">
							</ul>
						</li>
						<li class="dropdown first">
							<a href="/tGenre">TV-SERIES</a>
					</ul>

					<ul class="nav navbar-nav flex-child-menu menu-right">



						{% if user.is_authenticated %}
						<li><font color="Red"> Hi!{{ user.username }}</font></li>
						<li ><a href="/accounts/logout">LOG OUT</a></li>
						{% else %}
						<li ><a href="/accounts/login">LOG IN</a></li>


						<li ><a href="/signup">sign up</a></li>
						{% endif %}
					</ul>
				</div>

	    </nav>

	    <!-- top search form -->

	    <div class="top-search">
			<div class="col-md-6">
				<form action="{% url 'home:searchmovies' %}" method="GET">
					<input type="text" placeholder="Search Movies Here" name="query">
<!--					<input type="submit" value=" " >-->
				</form>
			</div>
			<div class="col-md-6">
				<form action="{% url 'home:searchseries' %}" method="GET">
					<input type="text" placeholder="Search TV Series Here" name="query">
<!--					<input type="submit" value=" " >-->
				</form>

			</div>
		</div>
</header>
<!-- END | Header -->

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="hero mv-single-hero">
	<div class="container">
		<div class="row">
			<div class="col-md-12">

                      <form style="border:1px solid #ccc width=100%" method="POST">
                      {% csrf_token %}
                      {% for message in messages %}
                      <p><font color="green">{{ message }}</font></p>
                      {% endfor %}
                      <div class="container">
<!--                      <h1>Sign Up</h1>-->
<!--                      <p>Please fill in this form to create an account.</p>-->
                      <hr>

                      <b>Username</b>
                      <input type="text" placeholder="Enter Username" name="username" required>

                      <b>Email</b>
                      <input type="text" placeholder="Enter Email" name="email" required>

                  <!--    <label for="password"><b>Password</b></label>-->
                      <b>Password</b>
                      <input type="password" placeholder="Enter Password" name="password" required>

                      <b>Repeat Password</b>
                      <input type="password" placeholder="Repeat Password" name="password1" required>

                  <!--    <label>-->
                  <!--      <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me-->
                  <!--    </label>-->

                      <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>

                      <div class="clearfix">
                        <button type="button" class="cancelbtn">Cancel</button>
                        <button type="submit" class="signupbtn">Sign Up</button>
                      </div>
                    </div>
                  </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}